SpiderFoodStore/Models/OrderInvoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SpiderFoodStore.Models
{
    public class OrderInvoice
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string OrderId { get; set; }
        public int CustomerId { get; set; }
        [Required]
        [DisplayName("Order date")]
        public DateTime OrderDate { get; set; }
        [Required]
        public decimal Total { get; set; }
        [Required]
        [DisplayName("Delivery date")]
        public DateTime DeliveryDate { get; set; }
        [DisplayName("Name of consignee")]
        public string NameOfConsignee { get; set; }
        [DisplayName("Address of consignee")]
        public string AddressOfConsignee { get; set; }
        [DisplayName("Phone of consignee")]
        public string PhoneOfConsignee { get; set; }
        [Required]
        [DisplayName("Delivered")]
        public bool isDelivered { get; set; }
        [Required]
        [DisplayName("Paid")]
        public bool isPaid { get; set; }
    }
}

SpiderFoodStore/Areas/QWRtaW5TcGlkZXI/Controllers/OrderInvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SpiderFoodStore.Data;
using SpiderFoodStore.Models;

namespace SpiderFoodStore.Areas.QWRtaW5TcGlkZXI.Controllers
{
    public class OrderInvoicesController : Controller
    {
        private SpiderFoodStoreContext db = new SpiderFoodStoreContext();

        // GET: QWRtaW5TcGlkZXI/OrderInvoices
        public ActionResult Index()
        {
            return View(db.OrderInvoices.OrderByDescending(n => n.OrderDate).ToList());
        }

        // GET: QWRtaW5TcGlkZXI/OrderInvoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderInvoice orderInvoice = db.OrderInvoices.Find(id);
            if (orderInvoice == null)
            {
                return HttpNotFound();
            }
            return View(orderInvoice);
        }

        // GET: QWRtaW5TcGlkZXI/OrderInvoices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QWRtaW5TcGlkZXI/OrderInvoices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerId,OrderDate,Total,DeliveryDate,NameOfConsignee,AddressOfConsignee,PhoneOfConsignee,isDelivered,isPaid")] OrderInvoice orderInvoice)
        {
            if (ModelState.IsValid)
            {
                db.OrderInvoices.Add(orderInvoice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(orderInvoice);
        }

        // GET: QWRtaW5TcGlkZXI/OrderInvoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderInvoice orderInvoice = db.OrderInvoices.Find(id);
            if (orderInvoice == null)
            {
                return HttpNotFound();
            }
            return View(orderInvoice);
        }

        // POST: QWRtaW5TcGlkZXI/OrderInvoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerId,OrderDate,Total,DeliveryDate,NameOfConsignee,AddressOfConsignee,PhoneOfConsignee,isDelivered,isPaid")] OrderInvoice orderInvoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderInvoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(orderInvoice);
        }

        // GET: QWRtaW5TcGlkZXI/OrderInvoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderInvoice orderInvoice = db.OrderInvoices.Find(id);
            if (orderInvoice == null)
            {
                return HttpNotFound();
            }
            return View(orderInvoice);
        }

        // POST: QWRtaW5TcGlkZXI/OrderInvoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderInvoice orderInvoice = db.OrderInvoices.Find(id);
            db.OrderInvoices.Remove(orderInvoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SpiderFoodStore/Areas/QWRtaW5TcGlkZXI/Views/OrderInvoices/Create.cshtml
@model SpiderFoodStore.Models.OrderInvoice

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/QWRtaW5TcGlkZXI/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>OrderInvoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameOfConsignee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameOfConsignee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameOfConsignee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressOfConsignee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressOfConsignee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressOfConsignee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneOfConsignee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneOfConsignee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneOfConsignee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDelivered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDelivered)
                    @Html.ValidationMessageFor(model => model.isDelivered, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isPaid)
                    @Html.ValidationMessageFor(model => model.isPaid, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success mt-3 mb-3"><i class="fa fa-floppy-o" aria-hidden="true"></i> Create</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-secondary", @role = "button" })
</div>

SpiderFoodStore/Areas/QWRtaW5TcGlkZXI/Views/OrderInvoices/Delete.cshtml
@model SpiderFoodStore.Models.OrderInvoice

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/QWRtaW5TcGlkZXI/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderInvoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameOfConsignee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameOfConsignee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressOfConsignee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressOfConsignee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneOfConsignee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneOfConsignee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDelivered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDelivered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isPaid)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" class="btn btn btn-danger mr-3"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
            @Html.ActionLink("Back to List", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-secondary", @role = "button" })
        </div>
    }
</div>

SpiderFoodStore/Areas/QWRtaW5TcGlkZXI/Views/OrderInvoices/Details.cshtml
@model SpiderFoodStore.Models.OrderInvoice

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/QWRtaW5TcGlkZXI/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Details</h2>

<div>
    <h4>OrderInvoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameOfConsignee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameOfConsignee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressOfConsignee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressOfConsignee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneOfConsignee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneOfConsignee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDelivered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDelivered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isPaid)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-warning mr-3", @role = "button" })
    @Html.ActionLink("Back to List", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-secondary", @role = "button" })
</p>

SpiderFoodStore/Areas/QWRtaW5TcGlkZXI/Views/OrderInvoices/Edit.cshtml
@model SpiderFoodStore.Models.OrderInvoice

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/QWRtaW5TcGlkZXI/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>OrderInvoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameOfConsignee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameOfConsignee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameOfConsignee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressOfConsignee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressOfConsignee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressOfConsignee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneOfConsignee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneOfConsignee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneOfConsignee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDelivered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDelivered)
                    @Html.ValidationMessageFor(model => model.isDelivered, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isPaid)
                    @Html.ValidationMessageFor(model => model.isPaid, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success mt-3 mb-3"><i class="fa fa-floppy-o" aria-hidden="true"></i> Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-secondary", @role = "button" })
</div>

SpiderFoodStore/Areas/QWRtaW5TcGlkZXI/Views/OrderInvoices/Index.cshtml
@model IEnumerable<SpiderFoodStore.Models.OrderInvoice>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/QWRtaW5TcGlkZXI/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("Create", "OrderInvoices")" class="btn btn-success" role="button">Create New</a>
</p>
<table class="table table-dark table-hover">
    <tr>
        <th>
            No.
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameOfConsignee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneOfConsignee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isDelivered)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isPaid)
        </th>
        <th></th>
    </tr>
    @{ int no = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{no++;}
                @no
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameOfConsignee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneOfConsignee)
            </td>
            <td>
                @if (item.isDelivered)
                {
                    <p><i class="fa fa-check-circle" aria-hidden="true" style="color: cadetblue; font-size: 18px;"></i></p>
                }
                else
                {
                    <p>-</p>
                }
            </td>
            <td>
                @if (item.isPaid)
                {
                    <p><i class="fa fa-check-circle" aria-hidden="true" style="color: cadetblue; font-size: 18px;"></i></p>
                }
                else
                {
                    <p>-</p>
                }
            </td>
            <td>
                <a href="@Url.Action("Edit", "OrderInvoices", new {id=item.Id})" class="btn btn-warning" role="button"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
                <a href="@Url.Action("Details", "OrderInvoices", new {id=item.Id})" class="btn btn-info" role="button"><i class="fa fa-info-circle" aria-hidden="true"></i> Details</a>
                <a href="@Url.Action("Delete", "OrderInvoices", new {id=item.Id})" class="btn btn-danger" role="button"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
            </td>
        </tr>
    }

</table>